INCLUDEPATH += $$PWD/libqtelegram/lib/

SOURCES  *= $$PWD/libqtelegram/lib/telegram.cpp \
            $$PWD/libqtelegram/lib/core/connection.cpp \
            $$PWD/libqtelegram/lib/core/settings.cpp \
            $$PWD/libqtelegram/lib/core/inboundpkt.cpp \
            $$PWD/libqtelegram/lib/core/outboundpkt.cpp \
            $$PWD/libqtelegram/lib/core/dcprovider.cpp \
            $$PWD/libqtelegram/lib/core/eventtimer.cpp \
            $$PWD/libqtelegram/lib/core/api.cpp \
            $$PWD/libqtelegram/lib/core/query.cpp \
            $$PWD/libqtelegram/lib/core/abstractapi.cpp \
            $$PWD/libqtelegram/lib/core/session.cpp \
            $$PWD/libqtelegram/lib/core/dcauth.cpp \
            $$PWD/libqtelegram/lib/core/sessionmanager.cpp \
            $$PWD/libqtelegram/lib/util/asserter.cpp \
            $$PWD/libqtelegram/lib/util/cryptoutils.cpp \
            $$PWD/libqtelegram/lib/util/utils.cpp \
            $$PWD/libqtelegram/lib/secret/decrypter.cpp \
            $$PWD/libqtelegram/lib/secret/encrypter.cpp \
            $$PWD/libqtelegram/lib/secret/secretstate.cpp \
            $$PWD/libqtelegram/lib/secret/secretchat.cpp \
            $$PWD/libqtelegram/lib/secret/decryptedmessagebuilder.cpp \
            $$PWD/libqtelegram/lib/file/filehandler.cpp \
            $$PWD/libqtelegram/lib/file/downloadfile.cpp \
            $$PWD/libqtelegram/lib/file/uploadfile.cpp

HEADERS  *= $$PWD/libqtelegram/lib/file/fileoperation.h \
            $$PWD/libqtelegram/lib/file/file.h \
            $$PWD/libqtelegram/lib/telegram.h \
            $$PWD/libqtelegram/lib/libqtelegram_global.h \
            $$PWD/libqtelegram/lib/core/abstractapi.h \
            $$PWD/libqtelegram/lib/core/eventtimer.h \
            $$PWD/libqtelegram/lib/core/dcprovider.h \
            $$PWD/libqtelegram/lib/core/outboundpkt.h \
            $$PWD/libqtelegram/lib/core/querymethods.h \
            $$PWD/libqtelegram/lib/core/query.h \
            $$PWD/libqtelegram/lib/core/connection.h \
            $$PWD/libqtelegram/lib/core/session.h \
            $$PWD/libqtelegram/lib/core/api.h \
            $$PWD/libqtelegram/lib/core/dc.h \
            $$PWD/libqtelegram/lib/core/dcauth.h \
            $$PWD/libqtelegram/lib/core/endpoint.h \
            $$PWD/libqtelegram/lib/core/sessionmanager.h \
            $$PWD/libqtelegram/lib/core/inboundpkt.h \
            $$PWD/libqtelegram/lib/core/settings.h \
            $$PWD/libqtelegram/lib/util/constants.h \
            $$PWD/libqtelegram/lib/util/cryptoutils.h \
            $$PWD/libqtelegram/lib/util/asserter.h \
            $$PWD/libqtelegram/lib/util/tlvalues.h \
            $$PWD/libqtelegram/lib/util/utils.h \
            $$PWD/libqtelegram/lib/types/document.h \
            $$PWD/libqtelegram/lib/types/geopoint.h \
            $$PWD/libqtelegram/lib/types/chatparticipants.h \
            $$PWD/libqtelegram/lib/types/inputfile.h \
            $$PWD/libqtelegram/lib/types/chatparticipant.h \
            $$PWD/libqtelegram/lib/types/video.h \
            $$PWD/libqtelegram/lib/types/dialog.h \
            $$PWD/libqtelegram/lib/types/peer.h \
            $$PWD/libqtelegram/lib/types/contactslink.h \
            $$PWD/libqtelegram/lib/types/chatlocated.h \
            $$PWD/libqtelegram/lib/types/audio.h \
            $$PWD/libqtelegram/lib/types/decryptedmessage.h \
            $$PWD/libqtelegram/lib/types/peernotifysettings.h \
            $$PWD/libqtelegram/lib/types/userprofilephoto.h \
            $$PWD/libqtelegram/lib/types/user.h \
            $$PWD/libqtelegram/lib/types/decryptedmessageaction.h \
            $$PWD/libqtelegram/lib/types/storagefiletype.h \
            $$PWD/libqtelegram/lib/types/contactsforeignlink.h \
            $$PWD/libqtelegram/lib/types/inputmedia.h \
            $$PWD/libqtelegram/lib/types/sendmessageaction.h \
            $$PWD/libqtelegram/lib/types/chatfull.h \
            $$PWD/libqtelegram/lib/types/messagemedia.h \
            $$PWD/libqtelegram/lib/types/messagesfilter.h \
            $$PWD/libqtelegram/lib/types/encryptedfile.h \
            $$PWD/libqtelegram/lib/types/inputcontact.h \
            $$PWD/libqtelegram/lib/types/decryptedmessagemedia.h \
            $$PWD/libqtelegram/lib/types/messageaction.h \
            $$PWD/libqtelegram/lib/types/inputnotifypeer.h \
            $$PWD/libqtelegram/lib/types/userstatus.h \
            $$PWD/libqtelegram/lib/types/inputuser.h \
            $$PWD/libqtelegram/lib/types/inputencryptedchat.h \
            $$PWD/libqtelegram/lib/types/encryptedchat.h \
            $$PWD/libqtelegram/lib/types/types.h \
            $$PWD/libqtelegram/lib/types/importedcontact.h \
            $$PWD/libqtelegram/lib/types/inputphoto.h \
            $$PWD/libqtelegram/lib/types/inputpeer.h \
            $$PWD/libqtelegram/lib/types/photo.h \
            $$PWD/libqtelegram/lib/types/wallpaper.h \
            $$PWD/libqtelegram/lib/types/inputpeernotifysettings.h \
            $$PWD/libqtelegram/lib/types/geochatmessage.h \
            $$PWD/libqtelegram/lib/types/message.h \
            $$PWD/libqtelegram/lib/types/contact.h \
            $$PWD/libqtelegram/lib/types/notifypeer.h \
            $$PWD/libqtelegram/lib/types/contactblocked.h \
            $$PWD/libqtelegram/lib/types/updatesstate.h \
            $$PWD/libqtelegram/lib/types/inputaudio.h \
            $$PWD/libqtelegram/lib/types/contactstatus.h \
            $$PWD/libqtelegram/lib/types/dcoption.h \
            $$PWD/libqtelegram/lib/types/inputchatphoto.h \
            $$PWD/libqtelegram/lib/types/inputphotocrop.h \
            $$PWD/libqtelegram/lib/types/photosize.h \
            $$PWD/libqtelegram/lib/types/chatphoto.h \
            $$PWD/libqtelegram/lib/types/update.h \
            $$PWD/libqtelegram/lib/types/filelocation.h \
            $$PWD/libqtelegram/lib/types/chat.h \
            $$PWD/libqtelegram/lib/types/inputdocument.h \
            $$PWD/libqtelegram/lib/types/encryptedmessage.h \
            $$PWD/libqtelegram/lib/types/contactsmylink.h \
            $$PWD/libqtelegram/lib/types/inputencryptedfile.h \
            $$PWD/libqtelegram/lib/types/inputgeopoint.h \
            $$PWD/libqtelegram/lib/types/inputfilelocation.h \
            $$PWD/libqtelegram/lib/types/inputvideo.h \
            $$PWD/libqtelegram/lib/types/inputgeochat.h \
            $$PWD/libqtelegram/lib/file/fileoperation.h \
            $$PWD/libqtelegram/lib/file/downloadfile.h \
            $$PWD/libqtelegram/lib/file/filehandler.h \
            $$PWD/libqtelegram/lib/file/file.h \
            $$PWD/libqtelegram/lib/file/uploadfile.h \
            $$PWD/libqtelegram/lib/secret/decrypter.h \
            $$PWD/libqtelegram/lib/secret/decryptedmessagebuilder.h \
            $$PWD/libqtelegram/lib/secret/encrypter.h \
            $$PWD/libqtelegram/lib/secret/secretchatmessage.h \
            $$PWD/libqtelegram/lib/secret/secretstate.h \
            $$PWD/libqtelegram/lib/secret/secretchat.h

LIBS     *= -lz -lrt -lssl -lcrypto
QT       *= network
